apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "git-agent-service-installer.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
