apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.portMgmt }}
      targetPort: mgmt
      protocol: TCP
      name: mgmt
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
